export const CONVEX_URL = process.env.NEXT_PUBLIC_CONVEX_URL!;

export const LIVEBLOCKS_PUBLIC_API_KEY =
  process.env.NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_API_KEY!;
export const LIVEBLOCKS_SECRET_KEY = process.env.LIVEBLOCKS_SECRET_KEY!;
